# Generated by Django 3.0.8 on 2020-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(default='', upload_to='database\\images')),
                ('student_name', models.TextField()),
                ('student_class', models.CharField(max_length=50)),
            ],
        ),
    ]
