# Generated by Django 3.0.8 on 2020-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_database_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='student_roll',
        ),
        migrations.AddField(
            model_name='database',
            name='student_roll_no',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
