# Generated by Django 3.0.8 on 2020-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200730_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_name',
            field=models.TextField(default=0),
        ),
    ]
