# Generated by Django 3.0.8 on 2020-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200730_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_roll_no',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
