# Generated by Django 3.0.8 on 2020-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200730_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='database',
            name='student_roll',
            field=models.IntegerField(default=0),
        ),
    ]
