# Generated by Django 3.0.8 on 2020-07-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200730_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='student_roll_no',
        ),
    ]
