# Generated by Django 3.0.8 on 2020-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200730_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_roll',
            field=models.IntegerField(null=True),
        ),
    ]
