# Generated by Django 3.0.8 on 2020-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_database_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_image',
            field=models.ImageField(default='https://us.123rf.com/450wm/apoev/apoev1903/apoev190300009/124806570-stock-vector-person-gray-photo-placeholder-man-in-t-shirt-on-gray-background.jpg?ver=6', upload_to='database\\images'),
        ),
    ]
