# Generated by Django 3.0.8 on 2020-08-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200801_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='student_image',
            field=models.ImageField(default='', upload_to='database\\images'),
        ),
    ]
